{
 "title": "Clio",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "connections_total_number{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "subscription_messages_total_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscriptions Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "subscriptions_current_number{job=\"clio\"}",
     "legendFormat": "{{collection}}{{stream}}"
    }
   ]
  },
  {
   "title": "Ledger Age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "timestamp(etl_last_publish_seconds) - etl_last_publish_seconds",
     "legendFormat": "ledger age"
    }
   ]
  },
  {
   "title": "Service state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"clio\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read only",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "read_only", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Writing data to DB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "etl_writing", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Amendment blocked",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "etl_amendment_blocked", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RPC Method Call Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(rpc_method_total_number{job=\"clio\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Work Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "work_queue_current_size{job=\"clio\"}",
     "legendFormat": "work queue size"
    }
   ]
  },
  {
   "title": "Ledger Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(ledger_cache_counter_total_number{job=\"clio\",type=\"cache_hit\"}[1m])) / sum(increase(ledger_cache_counter_total_number{job=\"clio\",type=\"request\"}[1m]))",
     "legendFormat": "ledger cache hit rate"
    }
   ]
  },
  {
   "title": "RPC Method Call Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (method) (increase(rpc_method_duration_us[$__interval]))\n / \n sum by (method,) (increase(rpc_method_total_number{status=\"finished\"}[$__interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RPC Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(rpc_error_total_number{job=\"clio\"}[$__rate_interval])",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  {
   "title": "DB Completed Operations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(backend_operations_total_number{job=\"clio\",status=\"completed\"}[$__rate_interval])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "DB operation duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(backend_duration_milliseconds_histogram_bucket{job=\"clio\"}[$__interval])) by (le, operation))",
     "legendFormat": "{{operation}} 0.5 percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(backend_duration_milliseconds_histogram_bucket{job=\"clio\"}[$__interval])) by (le, operation))",
     "legendFormat": "{{operation}} 0.75 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(backend_duration_milliseconds_histogram_bucket{job=\"clio\"}[$__interval])) by (le, operation))",
     "legendFormat": "{{operation}} 0.95 percentile"
    },
    {}
   ]
  },
  {
   "title": "DB Operations Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(backend_operations_total_number{job=\"clio\",status=~\"error|retry\"}[$__rate_interval])",
     "legendFormat": "{{operation}} {{status}}"
    },
    {
     "expr": "rate(backend_too_busy_total_number{job=\"clio\"}[$__rate_interval])",
     "legendFormat": "backend too_busy"
    }
   ]
  },
  {
   "title": "DB Pending operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "backend_operations_current_number{job=\"clio\",status=\"pending\"}",
     "legendFormat": "{{operation}}"
    },
    {}
   ]
  },
  {
   "title": "Prometheus Request Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"clio\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}